"""CHUNK-037 throwaway/reference implementation: extract literal
input/output examples from an acceptance-criteria text file and generate a
small, deterministic test module that checks them directly.

This exists because CHUNK-036 found that relying on an agent to remember
to include explicit-value checks in its own authored property test is not
enough -- an agent-authored test can look thematically complete and still
never exercise the exact input a surgical single-point cheat targets. The
fix decided in CHUNK-037: the framework itself parses whatever concrete
examples the *human-authored* acceptance criteria already states (these
already exist for documentation purposes in every acceptance-criteria
file this project has written) and generates a deterministic companion
check -- independent of, and in addition to, whatever the agent authors.

Deliberately simple: only handles the `` `func(args) == expected` ``
pattern already used in every acceptance_criteria.txt in this repo. Not a
general expression evaluator.
"""
from __future__ import annotations

import ast
import re
import textwrap
from dataclasses import dataclass

_EXAMPLE_RE = re.compile(r"`(\w+)\(([^`]*?)\)\s*==\s*([^`]*?)`")


@dataclass(frozen=True)
class LiteralExample:
    func: str
    args_src: str      # raw source of the argument list, e.g. "[1, 2, 3], 5"
    expected_src: str  # raw source of the expected value, e.g. "[3, 1, 2]"


def extract_literal_examples(acceptance_criteria_text: str) -> list[LiteralExample]:
    """Parse every backtick-quoted `func(args) == expected` example out of
    an acceptance-criteria text file. Validates that args/expected parse as
    Python literals (ast.literal_eval) so a malformed or non-literal match
    (e.g. prose that happens to contain `==`) is silently skipped rather
    than generating a broken check."""
    examples: list[LiteralExample] = []
    for match in _EXAMPLE_RE.finditer(acceptance_criteria_text):
        func, args_src, expected_src = match.group(1), match.group(2).strip(), match.group(3).strip()
        try:
            ast.parse(f"f({args_src})", mode="eval")
            ast.literal_eval(expected_src)
        except (SyntaxError, ValueError):
            continue
        examples.append(LiteralExample(func=func, args_src=args_src, expected_src=expected_src))
    return examples


def generate_literal_example_test(examples: list[LiteralExample], module: str) -> str:
    """Generate the source of a deterministic pytest module asserting each
    literal example directly -- no Hypothesis, no randomness. This is what
    actually catches a surgical single-point cheat targeting one of these
    exact inputs, per CHUNK-036's finding."""
    if not examples:
        return ""
    funcs = sorted({e.func for e in examples})
    lines = [
        '"""Auto-generated by phase4/literal_examples.py (CHUNK-037) from the',
        "literal examples already stated in acceptance_criteria.txt. Not",
        "agent-authored -- this file is deterministic and regenerated from the",
        'human-authored acceptance criteria every time, independent of any',
        'property test an agent writes.',
        '"""',
        f"from {module} import {', '.join(funcs)}",
        "",
    ]
    for i, ex in enumerate(examples):
        lines.append(f"def test_literal_example_{i}():")
        lines.append(f"    assert {ex.func}({ex.args_src}) == {ex.expected_src}")
        lines.append("")
    return "\n".join(lines)
