"""Auto-generated by phase4/literal_examples.py (CHUNK-037) from the
literal examples already stated in acceptance_criteria.txt. Not
agent-authored -- this file is deterministic and regenerated from the
human-authored acceptance criteria every time, independent of any
property test an agent writes.
"""
from listutils import rotate_left

def test_literal_example_0():
    assert rotate_left([1, 2, 3, 4, 5], 2) == [3, 4, 5, 1, 2]

def test_literal_example_1():
    assert rotate_left([1, 2, 3], 5) == [3, 1, 2]
